/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fd7613",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb68f",
        "on-background": "#1a1c1c",
        "tertiary-fixed": "#a3f69c",
        "background": "#f9f9f9",
        "on-secondary-fixed-variant": "#773200",
        "inverse-on-surface": "#f1f1f1",
        "primary-fixed": "#a6eff3",
        "primary-fixed-dim": "#8ad3d7",
        "primary-container": "#006064",
        "surface-bright": "#f9f9f9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005312",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#8ddf87",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#3f4949",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#6f7979",
        "surface-container": "#eeeeee",
        "primary": "#00464a",
        "on-primary-fixed": "#002021",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "tertiary-fixed-dim": "#88d982",
        "on-secondary-container": "#5b2500",
        "error": "#ba1a1a",
        "tertiary": "#004a0f",
        "on-secondary-fixed": "#331200",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#004f53",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002204",
        "inverse-primary": "#8ad3d7",
        "secondary-fixed": "#ffdbca",
        "secondary": "#9c4400",
        "on-primary-container": "#8fd8dc",
        "surface-dim": "#dadada",
        "inverse-surface": "#2f3131",
        "surface-tint": "#14696d",
        "outline-variant": "#bec8c9",
        "surface": "#f9f9f9",
        "tertiary-container": "#0f641c",
        "surface-container-low": "#f3f3f3"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}